CREATE DATABASE IF NOT EXISTS times_esportivos DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
USE times_esportivos;

CREATE TABLE IF NOT EXISTS time (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    data_inclusao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS jogadores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    time_id INT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    idade INT,
    perna VARCHAR(20) NOT NULL,
    posicao VARCHAR(50),
    data_inclusao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_time FOREIGN KEY (time_id) REFERENCES time(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
